<a href="https://colab.research.google.com/github/RonakkudalAI/Practical-Machine-Learning/blob/main/Weather_Data_(Data2)Set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/content/weather_data.csv")
df

         date  temperature  windspeed  humidity   event
0  2024-01-01           32          6        80    Rain
1  2024-01-02           35          7        70   Sunny
2  2024-01-03           28          2        90    Snow
3  2024-01-04           24          7        85    Snow
4  2024-01-05           32          4        75    Rain
5  2024-01-06           31          2        60   Sunny
6  2024-01-07           30          5        65  Cloudy
7  2024-01-08           29          3        88    Rain

In [ ]:
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         8 non-null      object
 1   temperature  8 non-null      int64
 2   windspeed    8 non-null      int64
 3   humidity     8 non-null      int64
 4   event        8 non-null      object
dtypes: int64(3), object(2)
memory usage: 452.0+ bytes

(8, 5)

In [ ]:
df.describe()

       temperature  windspeed  humidity
count     8.000000   8.000000   8.00000
mean     30.125000   4.500000  76.62500
std       3.270539   2.070197  11.00568
min      24.000000   2.000000  60.00000
25%      28.750000   2.750000  68.75000
50%      30.500000   4.500000  77.50000
75%      32.000000   6.250000  85.75000
max      35.000000   7.000000  90.00000

In [ ]:
df.head()

         date  temperature  windspeed  humidity  event
0  2024-01-01           32          6        80   Rain
1  2024-01-02           35          7        70  Sunny
2  2024-01-03           28          2        90   Snow
3  2024-01-04           24          7        85   Snow
4  2024-01-05           32          4        75   Rain

In [ ]:
print(df["temperature"].min())
print(df['temperature'].max())

24
35

In [ ]:
print(df["temperature"].mean())
print(df["temperature"].median())

30.125
30.5

In [ ]:
print(df["windspeed"].mean())

4.5

In [ ]:
df[df["windspeed"]>5]

         date  temperature  windspeed  humidity  event
0  2024-01-01           32          6        80   Rain
1  2024-01-02           35          7        70  Sunny
3  2024-01-04           24          7        85   Snow

In [ ]:
#Humidity Analysis
print(df['humidity'].mean())

76.625

In [ ]:
df[df["humidity"]>80]

         date  temperature  windspeed  humidity event
2  2024-01-03           28          2        90  Snow
3  2024-01-04           24          7        85  Snow
7  2024-01-08           29          3        88  Rain

In [ ]:
df['event'].value_counts()

event
Rain      3
Sunny     2
Snow      2
Cloudy    1
Name: count, dtype: int64

In [ ]:
from datetime import date
#Data Preprocessing
df['date'] = pd.to_datetime(df["date"])

In [ ]:
# Extract day and months
df["day"] = df["date"].dt.day

In [ ]:
# Extract day and months
df["day"] = df["date"].dt.month

In [ ]:
df

        date  temperature  windspeed  humidity   event  day
0 2024-01-01           32          6        80    Rain    1
1 2024-01-02           35          7        70   Sunny    1
2 2024-01-03           28          2        90    Snow    1
3 2024-01-04           24          7        85    Snow    1
4 2024-01-05           32          4        75    Rain    1
5 2024-01-06           31          2        60   Sunny    1
6 2024-01-07           30          5        65  Cloudy    1
7 2024-01-08           29          3        88    Rain    1

In [ ]:
# Temperature in Faraneit
df["tempf"] = (df["temperature"]*9/5)+32
df

        date  temperature  windspeed  humidity   event  day  tempf
0 2024-01-01           32          6        80    Rain    1   89.6
1 2024-01-02           35          7        70   Sunny    1   95.0
2 2024-01-03           28          2        90    Snow    1   82.4
3 2024-01-04           24          7        85    Snow    1   75.2
4 2024-01-05           32          4        75    Rain    1   89.6
5 2024-01-06           31          2        60   Sunny    1   87.8
6 2024-01-07           30          5        65  Cloudy    1   86.0
7 2024-01-08           29          3        88    Rain    1   84.2

In [ ]:
df.groupby("event")["temperature"].mean()

event
Cloudy    30.0
Rain      31.0
Snow      26.0
Sunny     33.0
Name: temperature, dtype: float64

In [ ]:
df.groupby("event")["humidity"].max()

event
Cloudy    65
Rain      88
Snow      90
Sunny     70
Name: humidity, dtype: int64

In [ ]:
df[(df["event"]== "Sunny") & (df["temperature"]>30)]

        date  temperature  windspeed  humidity  event  day  tempf
1 2024-01-02           35          7        70  Sunny    1   95.0
5 2024-01-06           31          2        60  Sunny    1   87.8

In [ ]:
#Sort OurData Set Asc
df.sort_values("temperature")

        date  temperature  windspeed  humidity   event  day  tempf
3 2024-01-04           24          7        85    Snow    1   75.2
2 2024-01-03           28          2        90    Snow    1   82.4
7 2024-01-08           29          3        88    Rain    1   84.2
6 2024-01-07           30          5        65  Cloudy    1   86.0
5 2024-01-06           31          2        60   Sunny    1   87.8
0 2024-01-01           32          6        80    Rain    1   89.6
4 2024-01-05           32          4        75    Rain    1   89.6
1 2024-01-02           35          7        70   Sunny    1   95.0

In [ ]:
#Sort OurData Set Desc
df.sort_values("temperature",ascending=False)

        date  temperature  windspeed  humidity   event  day  tempf
1 2024-01-02           35          7        70   Sunny    1   95.0
0 2024-01-01           32          6        80    Rain    1   89.6
4 2024-01-05           32          4        75    Rain    1   89.6
5 2024-01-06           31          2        60   Sunny    1   87.8
6 2024-01-07           30          5        65  Cloudy    1   86.0
7 2024-01-08           29          3        88    Rain    1   84.2
2 2024-01-03           28          2        90    Snow    1   82.4
3 2024-01-04           24          7        85    Snow    1   75.2