In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.metrics import mean_squared_error

In [ ]:
data={"weather":['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny',
'Rainy','Sunny','Overcast','Overcast','Rainy'],
"temp":['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild'],

"play":['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']

}

In [ ]:
df=pd.DataFrame(data)
df

     weather  temp play
0      Sunny   Hot   No
1      Sunny   Hot   No
2   Overcast   Hot  Yes
3      Rainy  Mild  Yes
4      Rainy  Cool  Yes
5      Rainy  Cool   No
6   Overcast  Cool  Yes
7      Sunny  Mild   No
8      Sunny  Cool  Yes
9      Rainy  Mild  Yes
10     Sunny  Mild  Yes
11  Overcast  Mild  Yes
12  Overcast   Hot  Yes
13     Rainy  Mild   No

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [ ]:
df['temp']=le.fit_transform(df['temp'])
df['weather']=le.fit_transform(df['weather'])
df['play']=le.fit_transform(df['play'])

In [ ]:
df

    weather  temp  play
0         2     1     0
1         2     1     0
2         0     1     1
3         1     2     1
4         1     0     1
5         1     0     0
6         0     0     1
7         2     2     0
8         2     0     1
9         1     2     1
10        2     2     1
11        0     2     1
12        0     1     1
13        1     2     0

In [ ]:
df.isnull().sum()

weather    0
temp       0
play       0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(3)

In [ ]:
#remove duplicate
df.drop_duplicates(inplace=True)

In [ ]:
df

    weather  temp  play
0         2     1     0
2         0     1     1
3         1     2     1
4         1     0     1
5         1     0     0
6         0     0     1
7         2     2     0
8         2     0     1
10        2     2     1
11        0     2     1
13        1     2     0

In [ ]:
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
#Scaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [ ]:
#Knn algorithm
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [ ]:
y_pred=knn.predict(X_test)
y_pred

array([1, 1, 1])

In [ ]:
#accuracy
knn_acc=accuracy_score(y_test,y_pred)
knn_acc

0.6666666666666666

Ex Naive Bayes spam Classifier

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

In [ ]:
emails = [
    "free money now",              # spam
    "win a lottery prize",        # spam
    "claim your free offer",      # spam
    "meeting scheduled tomorrow",  # ham
    "project discussion today",    # ham
    "let's have lunch tomorrow",   # ham
    "win free cash prize",         # spam
    "team meeting agenda",         # ham
]

labels = [1, 1, 1, 0, 0, 0, 1, 0]

In [ ]:
# Convert text into numerical feature(Bag of words)
vectorizer=CountVectorizer()
X=vectorizer.fit_transform(emails)

In [ ]:
#split dataset
X_train,X_test,y_train,y_test=train_test_split(X,labels,test_size=0.2,random_state=42)

In [ ]:
#apply algorithm
model=MultinomialNB()
model.fit(X_train,y_train)

MultinomialNB()

In [ ]:
y_pred=model.predict(X_test)
y_pred

array([1, 0])

In [ ]:
acuury_multi=accuracy_score(y_test,y_pred)
acuury_multi

1.0